// Environment variables - use process.env directly
export const THIRDWEB_API_BASE_URL = process.env.THIRDWEB_API_BASE_URL || "https://api.thirdweb.com";
export const THIRDWEB_SECRET_KEY = process.env.THIRDWEB_SECRET_KEY || "";
export const THIRDWEB_CLIENT_ID = process.env.NEXT_PUBLIC_THIRDWEB_CLIENT_ID || "";
export const TOKEN_CONTRACT_ADDRESS = process.env.TOKEN_CONTRACT_ADDRESS || "0x15536ea8CcAEB134BD2FCd6E9E126C2F935eb7F0";
export const QUEST_CONTRACT_ADDRESS = process.env.QUEST_CONTRACT_ADDRESS || "0x09706f60CAbdE6a58abaA46647264Ea904859276";
export const CHAIN_ID = process.env.CHAIN_ID || "84532";
export const ADMIN_ADDRESS = process.env.ADMIN_ADDRESS || "";
export const GAME_REWARD_BASE = parseInt(process.env.GAME_REWARD_BASE || "100");
export const GAME_REWARD_MAX = parseInt(process.env.GAME_REWARD_MAX || "500");
export const GAME_VERIFICATION_WINDOW = parseInt(process.env.GAME_VERIFICATION_WINDOW || "86400000");
